// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfJOTWpG8S2yNz6cKAKaoSE0iR5-XWBI',
    appId: '1:657219334090:web:be4ce84e6b80cb8d2e2933',
    messagingSenderId: '657219334090',
    projectId: 'hajato-app',
    authDomain: 'hajato-app.firebaseapp.com',
    storageBucket: 'hajato-app.firebasestorage.app',
    measurementId: 'G-YRYRXQ6V7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLXFP7kEJ9V7pZ3VNOvdT32NX14Cxbtkw',
    appId: '1:657219334090:android:67e33ec720b6299c2e2933',
    messagingSenderId: '657219334090',
    projectId: 'hajato-app',
    storageBucket: 'hajato-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmj4zY2GRHDxo8LSZCxiz1LQvOo6HoXoU',
    appId: '1:657219334090:ios:34927474e89f6ab32e2933',
    messagingSenderId: '657219334090',
    projectId: 'hajato-app',
    storageBucket: 'hajato-app.firebasestorage.app',
    androidClientId: '657219334090-rlov1s3e75u8qj69d5il3ts4m2v17sid.apps.googleusercontent.com',
    iosClientId: '657219334090-ln1857egm6laduugcg003vmqffuuhng3.apps.googleusercontent.com',
    iosBundleId: 'com.hajato.hajato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmj4zY2GRHDxo8LSZCxiz1LQvOo6HoXoU',
    appId: '1:657219334090:ios:34927474e89f6ab32e2933',
    messagingSenderId: '657219334090',
    projectId: 'hajato-app',
    storageBucket: 'hajato-app.firebasestorage.app',
    androidClientId: '657219334090-rlov1s3e75u8qj69d5il3ts4m2v17sid.apps.googleusercontent.com',
    iosClientId: '657219334090-ln1857egm6laduugcg003vmqffuuhng3.apps.googleusercontent.com',
    iosBundleId: 'com.hajato.hajato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRfJOTWpG8S2yNz6cKAKaoSE0iR5-XWBI',
    appId: '1:657219334090:web:6c97779cc3dbf98b2e2933',
    messagingSenderId: '657219334090',
    projectId: 'hajato-app',
    authDomain: 'hajato-app.firebaseapp.com',
    storageBucket: 'hajato-app.firebasestorage.app',
    measurementId: 'G-B81J9VQBFJ',
  );
}
